# Generated by Django 6.0.3 on 2026-04-01 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('encryption', '0003_encryptionkey_key_type_encryptionkey_revoked_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='encryption_key',
            field=models.ForeignKey(blank=True, help_text='Encryption key used for this document', null=True, on_delete=django.db.models.deletion.PROTECT, to='encryption.encryptionkey'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='integrity_check',
            field=models.ForeignKey(blank=True, help_text='Integrity check result for this version', null=True, on_delete=django.db.models.deletion.SET_NULL, to='encryption.integritycheck'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['owner', 'is_deleted'], name='documents_d_owner_i_931eb7_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['category', 'created_at'], name='documents_d_categor_506bed_idx'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['document', 'version_number'], name='documents_d_documen_68fe34_idx'),
        ),
    ]
