# Generated by Django 6.0.3 on 2026-04-02 13:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_encryption_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_token', models.CharField(help_text='Secure token for accessing shared document', max_length=64, unique=True)),
                ('permission', models.CharField(choices=[('view', 'View Only'), ('download', 'View & Download')], default='view', help_text='Permission level for shared access', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the share link expires (null for no expiry)', null=True)),
                ('max_downloads', models.PositiveIntegerField(blank=True, help_text='Maximum number of downloads allowed (null for unlimited)', null=True)),
                ('download_count', models.PositiveIntegerField(default=0, help_text='Number of times the document has been downloaded')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the share link is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='documents.document')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['share_token'], name='documents_d_share_t_57bd35_idx'), models.Index(fields=['document', 'is_active'], name='documents_d_documen_c67e82_idx'), models.Index(fields=['expires_at'], name='documents_d_expires_4b27d0_idx')],
            },
        ),
    ]
