# Generated by Django 6.0.3 on 2026-04-01 13:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('file_access', 'File Access'), ('file_upload', 'File Upload'), ('file_download', 'File Download'), ('file_delete', 'File Delete'), ('permission_change', 'Permission Change'), ('user_create', 'User Created'), ('user_update', 'User Updated'), ('user_delete', 'User Deleted'), ('encryption_key_generate', 'Encryption Key Generated'), ('encryption_key_revoke', 'Encryption Key Revoked'), ('encryption_key_rotate', 'Encryption Key Rotated'), ('encryption_operation', 'Encryption Operation'), ('decryption_operation', 'Decryption Operation'), ('integrity_check', 'Integrity Check'), ('integrity_failure', 'Integrity Failure'), ('system_backup', 'System Backup'), ('system_restore', 'System Restore'), ('config_change', 'Configuration Change'), ('security_event', 'Security Event'), ('api_access', 'API Access'), ('data_export', 'Data Export'), ('data_import', 'Data Import')], help_text='Type of audit event', max_length=50)),
                ('event_description', models.TextField(help_text='Detailed description of the event')),
                ('resource_type', models.CharField(blank=True, help_text='Type of resource affected (file, user, key, etc.)', max_length=100)),
                ('resource_id', models.CharField(blank=True, help_text='ID of the affected resource', max_length=100)),
                ('old_value', models.TextField(blank=True, help_text='Previous value before the change', null=True)),
                ('new_value', models.TextField(blank=True, help_text='New value after the change', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string')),
                ('session_key', models.CharField(blank=True, help_text='Session identifier', max_length=100)),
                ('success', models.BooleanField(default=True, help_text='Whether the operation was successful')),
                ('error_message', models.TextField(blank=True, help_text='Error message if operation failed', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional event metadata as JSON')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='audit_audit_user_id_e8be02_idx'), models.Index(fields=['event_type', 'timestamp'], name='audit_audit_event_t_aa07a6_idx'), models.Index(fields=['resource_type', 'resource_id'], name='audit_audit_resourc_2a3aef_idx'), models.Index(fields=['timestamp'], name='audit_audit_timesta_19e18a_idx')],
            },
        ),
    ]
