# Generated by Django 6.0.3 on 2026-04-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryption', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptionalgorithm',
            name='mode',
            field=models.CharField(choices=[('fernet', 'Fernet (Standard Security)'), ('aes_cbc', 'AES-CBC (High Security)')], default='fernet', max_length=20),
        ),
    ]
