# Generated by Django 6.0.3 on 2026-04-01 13:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryption', '0002_encryptionalgorithm_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptionkey',
            name='key_type',
            field=models.CharField(choices=[('symmetric', 'Symmetric Key'), ('asymmetric_public', 'Asymmetric Public Key'), ('asymmetric_private', 'Asymmetric Private Key')], default='symmetric', max_length=20),
        ),
        migrations.AddField(
            model_name='encryptionkey',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encryptionkey',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_keys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='keyusagelog',
            name='action',
            field=models.CharField(choices=[('encrypt', 'Encrypt'), ('decrypt', 'Decrypt'), ('generate', 'Generate'), ('rotate', 'Rotate'), ('revoke', 'Revoke'), ('INTEGRITY_FAIL', 'Integrity Failure')], max_length=20),
        ),
        migrations.CreateModel(
            name='IntegrityCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=500)),
                ('original_checksum', models.CharField(help_text='SHA-256 checksum of original file', max_length=64)),
                ('encrypted_checksum', models.CharField(blank=True, help_text='SHA-256 checksum of encrypted file', max_length=64)),
                ('decrypted_checksum', models.CharField(blank=True, help_text='SHA-256 checksum after decryption', max_length=64)),
                ('check_passed', models.BooleanField(default=True)),
                ('check_timestamp', models.DateTimeField(auto_now_add=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('encryption_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encryption.encryptionkey')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Integrity Check',
                'verbose_name_plural': 'Integrity Checks',
                'ordering': ['-check_timestamp'],
            },
        ),
    ]
